casu/casu/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'casu.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'casu.views.home', name='home'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^imagedb/', include('imagedb.urls', namespace='imagedb')),

)

casu/imagedb/urls.py
from django.conf.urls import patterns, url

from imagedb import views

urlpatterns = patterns('',
    url(r'^index$', views.index, name='index'),
    url(r'^getImageLocal$', views.getImageLocal, name='getImageLocal'),
    url(r'^getImageCache/(?P<md5hash>\S+)$', views.getImageCache, name='getImageCache'),
    url(r'^getImage$', views.getImage, name='getImage'),
    url(r'^collection', views.collection, name='collection'),
    url(r'^getTar/(?P<md5hash>\S+)$', views.getTar, name='getTar'),
    url(r'^showField', views.showField, name='showField'),
    url(r'^getStatus/(?P<id>\S+)$', views.getStatus, name='getStatus'),
)

casu/casu/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def home(request):
    return HttpResponse("Hello, world. You're at the imagedb index.")

casu/casu/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<!-- https://github.com/tedtieken/django-slingshot/blob/master/templatetemplates/magazine/templates/base.html -->

        {% load active from navigation %}

		{% load staticfiles %}
		
		{% block css %}
		<link rel="stylesheet" type="text/css" href="{% static 'casu/style.css' %}" />
		{% block css.extra %}{% endblock css.extra %}
		{% endblock css %}
		
		{% block js %}
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
		{% block js.extra %}{% endblock js.extra %}
		{% endblock js %}
		
		{% block head.extra %}
		{% endblock head.extra %}
		
	</head>
	
	{% block body %}
	<body>
	
	{% block header %}
		<div id="header">
            <div id="auth" style="position: absolute; color: white; padding: 0em 2em; font-size: 8pt; top: -2em; right: 0px">
            {% if user.is_authenticated %}
                You are logged is as <span style="color: yellow">{{ user.username }}</span>&nbsp;&nbsp;
                <a style="color: white; text-decoration: none" href="{% url 'logout'  %}?next={{request.get_full_path}}">[Logout]</a>
            {% else %}
                <a style="color: white; text-decoration: none" href="{% url 'login'  %}?next={{request.get_full_path}}">Login</a>
            {% endif %}
            </div>

			<div id="sitetitle">{% block sitetitle %}Site Title{% endblock sitetitle %} &nbsp; &nbsp; ::: </div>

            <div id='cssmenu'>

                <ul>
                   <li class='{% active 'pages-pages' %}'><a href="{% url 'imagedb:index' %}"><span>Home</span></a></li>
                   <li class='{% active 'collection' %}'><a href="{% url 'imagedb:collection' %}"><span>Collections</span></a></li>
                   <li class='{% active 'getImage' %}'><a href="{% url 'imagedb:getImage' %}"><span>Stamps</span></a></li>
                   <li><a href='#'><span>About</span></a></li>
                   <li class='last'><a href='#'><span></span></a></li>
                </ul>

            </div>
		</div>

            <div id="pagename">{% block pagename %}{% endblock pagename %}</div>

	{% endblock header %}

	<div id="contents" class="container" style="min-height: 400px;">


        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

		{% block content %}<p>ERROR: No contents found for specified URL.</p>{% endblock content %}

	</div>

	</body>
	{% endblock body %}	
</html>