casu/casu/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'casu.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'casu.views.home', name='home'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^imagedb/', include('imagedb.urls', namespace='imagedb')),

)

casu/imagedb/urls.py
from django.conf.urls import patterns, url

from imagedb import views

urlpatterns = patterns('',
    url(r'^index$', views.index, name='index'),
    url(r'^getImageLocal$', views.getImageLocal, name='getImageLocal'),
    url(r'^getImageCache/(?P<md5hash>\S+)$', views.getImageCache, name='getImageCache'),
    url(r'^getImage$', views.getImage, name='getImage'),
    url(r'^collection', views.collection, name='collection'),
    url(r'^getTar/(?P<md5hash>\S+)$', views.getTar, name='getTar'),
    url(r'^showField', views.showField, name='showField'),
    url(r'^getStatus/(?P<id>\S+)$', views.getStatus, name='getStatus'),
)

casu/imagedb/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Config(models.Model):
    pathRequest = models.CharField(max_length=200)
    pathCache = models.CharField(max_length=200)


class Request(models.Model):
    ip = models.CharField(max_length=60)
    ra = models.FloatField()
    dec = models.FloatField()
    size = models.FloatField()
    options = models.CharField(max_length=20)
    success = models.BooleanField()
    md5hash = models.CharField(max_length=80)

    date = models.DateTimeField(default=datetime.now, blank=True)
    userAnonymous = models.BooleanField()
    userName = models.CharField(max_length=16, null=True)
    userGroup = models.CharField(max_length=80, null=True)


class Cache(models.Model):
    path = models.CharField(max_length=200)
    hdu = models.PositiveSmallIntegerField()

    md5hash = models.CharField(max_length=80)

    image = models.IntegerField(null=True)

    annotation = models.CharField(max_length=256, null=True)

    waveband = models.CharField(max_length=40)
    telescope = models.CharField(max_length=40)
    instrument = models.CharField(max_length=40)
    # seeing = models.FloatField(null=True)
    # skynoise = models.FloatField(null=True)
    #pixscl = models.FloatField()

    request = models.ForeignKey('Request')


class Collection(models.Model):
    cnum = models.IntegerField()
    field = models.CharField(max_length=20)
    subfield = models.CharField(max_length=20, null=True)
    survey = models.CharField(max_length=60)
    telescope = models.CharField(max_length=60)
    instrument = models.CharField(max_length=60)
    proposal = models.CharField(max_length=60, null=True)
    area = models.FloatField(null=True)
    cenra = models.FloatField(null=True)
    cendec = models.FloatField(null=True)
    wavelength = models.FloatField(null=True)
    filter = models.CharField(max_length=20)
    status = models.CharField(max_length=20)
    depth = models.FloatField(null=True)
    units = models.CharField(max_length=20, null=True)
    pi = models.CharField(max_length=60, null=True)
    reference = models.CharField(max_length=60, null=True)
    url = models.CharField(max_length=60, null=True)
    addinfo = models.CharField(max_length=256)


class Image(models.Model):
    filename = models.CharField(max_length=80)
    filepath = models.CharField(max_length=256)
    objname = models.CharField(max_length=40)
    extno = models.IntegerField()
    dateobs = models.DateTimeField(null=True)
    waveband = models.CharField(max_length=40)
    telescope = models.CharField(max_length=40)
    instrument = models.CharField(max_length=40)
    origin = models.CharField(max_length=40)
    observatory = models.CharField(max_length=40)
    mjd = models.FloatField()
    exptime = models.FloatField()
    seeing = models.FloatField(null=True)
    elliptic = models.FloatField(null=True)
    airmass = models.FloatField()
    maglim = models.FloatField(null=True)
    magzpt = models.FloatField(null=True)
    magzrr = models.FloatField(null=True)
    skynoise = models.FloatField(null=True)
    naxis1 = models.IntegerField()
    naxis2 = models.IntegerField()
    ctype1 = models.CharField(max_length=8)
    ctype2 = models.CharField(max_length=8)
    crpix1 = models.FloatField()
    crpix2 = models.FloatField()
    crval1 = models.FloatField()
    crval2 = models.FloatField()
    cd11 = models.FloatField()
    cd12 = models.FloatField()
    cd21 = models.FloatField()
    cd22 = models.FloatField()
    pv21 = models.FloatField(null=True)
    pv22 = models.FloatField(null=True)
    pv23 = models.FloatField(null=True)
    pv24 = models.FloatField(null=True)
    pv25 = models.FloatField(null=True)
    cenra = models.FloatField()
    cendec = models.FloatField()
    cencoords = models.CharField(max_length=30)
    pixscl = models.FloatField()
    addinfo = models.CharField(max_length=256)

    hascat = models.BooleanField()
    catname = models.CharField(max_length=80, null=True)

    groupname = models.CharField(max_length=256)
    seqn = models.IntegerField()
    ishidden = models.BooleanField(default=False)

    collection = models.ForeignKey('Collection')



    
    
    
    

casu/imagedb/views.py
import os
import time
import base64
import json

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.db.models import Max, Min
from django.views.decorators.cache import cache_page

from celery.result import AsyncResult

from imagedb.models import Request, Image, Cache, Collection
from imagedb.utils import ImageDict, SortKey, isMobile
from imagedb.settings import CACHE, REQUESTS

from casu.celery import app
from imagedb.tasks import computemd5
from PIL import Image as PILImage
from casu.settings import ALLOWED_HOSTS

# Create your views here.
def index(request):
    context={}
    return render(request, "imagedb/index.html", context)

@cache_page(60 * 60)
def collection(request):
    """
    Displays the list of image collections
    :param request:
    :return:
    """
    context={}

    try:
        context = json.load(open('/tmp/collections.pkl'))
    except:
        c = []
        result = Collection.objects.all()
        totalimages = 0
        for r in result:
            dd = ImageDict()
            for k in ['field', 'addinfo', 'survey', 'telescope', 'instrument', 'filter', 'status', 'pi']:
                dd[k] = getattr(r, k)
            dd['number'] = Image.objects.filter(collection = r.id).filter(ishidden=False).count()
            totalimages = totalimages + dd['number']
            dd.update(Image.objects.filter(collection = r.id).filter(ishidden=False).aggregate(Min('cenra')))
            dd.update(Image.objects.filter(collection = r.id).filter(ishidden=False).aggregate(Max('cenra')))
            dd.update(Image.objects.filter(collection = r.id).filter(ishidden=False).aggregate(Min('cendec')))
            dd.update(Image.objects.filter(collection = r.id).filter(ishidden=False).aggregate(Max('cendec')))
            c.append(dd)

        context['collection'] = c
        context['totalimages'] = totalimages

        json.dump(context,open('/tmp/collections.pkl','w'))

    return render(request, "imagedb/collection.html", context)

def getTar(request, md5hash):
    pass

def getImage(request):
    """

    :param request:
    :return:

    Example:

        http://apm14.ast.cam.ac.uk/imagedb/getImage?ra=242.0&dec=54.8&size=120.0&options=
    """
    ip = request.META['REMOTE_ADDR']
    if isMobile(request):
        template_name = 'imagedb/m_getimage.html'
    else:
        template_name = 'imagedb/getimage.html'

    # Get is a direct call
    if request.META['REQUEST_METHOD'] == 'POST':
        args = request.POST
    else:
        args = request.GET

    # Copy all arguments to own dictionary, because args is immutable
    context = {}
    for k in args.keys():
        context[k] = args[k]
        request.session[k] = args[k]

    # Check if we have all inputs, otherwise go back to the form
    try:
        ra, dec, size, options = args['ra'], args['dec'], args['size'], args['options']
        ra = float(ra)
        dec = float(dec)
        size = float(size)
    except:
        for k in ['ra', 'dec', 'size', 'options']:
            context[k] = request.session.get(k, None)
            if context[k] is None: context.pop(k)
            context['celeryID']=0
        return render(request, template_name, context)

    # Perform database query and get results
    result = Image.objects.all().filter(cendec__gt=dec - 1, cendec__lt=dec + 1, cenra__gt=ra - 1, cenra__lt=ra + 1).filter(ishidden=False)
    onchip = "onchip(%s,%s,naxis1, naxis2, ctype1, ctype2, crval1, crval2, crpix1, crpix2, cd11, cd12, cd21, cd22, pv21, pv23, pv25)=true" % (
    ra, dec)
    result = result.extra(where=[onchip])

    # Compute unique md5 from the argument list
    md5unique = computemd5((ra, dec, size, options.replace('U', '')))

    # Save request to database
    req = Request(ip=ip, ra=ra, dec=dec, size=size, options=options, success=False, userAnonymous=True,
                  md5hash=md5unique)
    if request.user.is_authenticated():
        req.userAnonymous = False
        req.userName = request.user.username
        req.userGroup = ' '.join([g.name for g in request.user.groups.all()])
        md5unique = computemd5((ra, dec, size, options.replace('U', ''), req.userGroup))
        req.md5hash = md5unique

    req.save()

    # Save the unique md5 of the request in the session
    request.session["md5unique"] = md5unique
    context["md5unique"] = md5unique

    outputDir = os.path.join(REQUESTS, '%010d' % req.id)
    if not os.access(outputDir, os.X_OK):
        os.mkdir(outputDir)
        os.chmod(outputDir, 0777)

    # Get full list of images
    flag = False
    keys = [f.name for f in Image._meta.fields]
    images = []
    for img in result:
        dd = ImageDict()
        for k in keys:
            dd[k] = getattr(img, k)
        md5hash = computemd5(
            (ra, dec, os.path.join(img.filepath, img.filename), size, img.extno, options.replace('U', '')))
        dd['md5hash'] = md5hash
        # Work out if the user has access rights
        dd['avail'] = False

        #print [g.name for g in request.user.groups.all()], img.groupname
        if ip in ALLOWED_HOSTS:
            dd['avail'] = True
        elif (img.groupname == 'public'):
            dd['avail'] = True
        else:
            if request.user.is_authenticated():
                groups = [g.name for g in request.user.groups.all()]
                if 'casuadmin' in groups:
                    dd['avail'] = True
                elif img.groupname in groups:
                    dd['avail'] = True
        images.append(dd)
        if dd['avail']:
            flag = True
            ch = Cache(request=req, path=os.path.join(img.filepath, img.filename), hdu=img.extno, image=img.id,
                       waveband = img.waveband, telescope = img.telescope, instrument = img.instrument,
                       md5hash=dd['md5hash'])
            ch.save()

    images.sort(key=SortKey)

    # Write unique md5
    fh = open(os.path.join(outputDir, 'md5unique'), 'w').write(md5unique)

    # Check if we can make colour VISTA image ---------------------------------
    context['vistaRGB'] = None

    bands = ['Ks', 'H', 'J', 'Y', 'Z']
    cbands = []
    for i in range(len(images)):
        if images[i].instrument.find('VIRCAM')<0: continue
        if not images[i]['avail']: continue
        if images[i].waveband in bands:
                if images[i].waveband in cbands:
                    pass
                else:
                    cbands.append(images[i].waveband)
        if len(cbands)==3: break

    if len(cbands) == 3:
        context['vistaRGB'] = 'rgbv%s' % md5unique
        context['vistaBands'] = ' '.join(cbands)
    # -------------------------------------------------------------------------

    # Check if we can make colour VST image ---------------------------------
    context['vstRGB'] = None

    bands = ['i_SDSS', 'r_SDSS', 'g_SDSS', 'u_SDSS']
    cbands = []
    for i in range(len(images)):
        if images[i].instrument.find('OMEGACAM')<0: continue
        if not images[i]['avail']: continue
        if images[i].waveband in bands:
                if images[i].waveband in cbands:
                    pass
                else:
                    cbands.append(images[i].waveband)
        if len(cbands)==3: break

    if len(cbands) == 3:
        context['vstRGB'] = 'rgbo%s' % md5unique
        context['vstBands'] = ' '.join(cbands)
    # -------------------------------------------------------------------------

    # Check if we can make colour WFC image ---------------------------------
    context['wfcRGB'] = None

    bands = ['i', 'r', 'g', 'u']
    cbands = []
    for i in range(len(images)):
        if images[i].instrument.find('WFC')<0: continue
        if not images[i]['avail']: continue
        if images[i].waveband in bands:
                if images[i].waveband in cbands:
                    pass
                else:
                    cbands.append(images[i].waveband)
        if len(cbands)==3: break

    if len(cbands) == 3:
        context['wfcRGB'] = 'rgbw%s' % md5unique
        context['wfcBands'] = ' '.join(cbands)
    # -------------------------------------------------------------------------

    # Check if we can make colour IRAC image ---------------------------------
    context['iracRGB'] = None

    bands = ['IRAC3', 'IRAC2', 'IRAC1']
    cbands = []
    for i in range(len(images)):
        if images[i].instrument.find('IRAC')<0: continue
        if not images[i]['avail']: continue
        if images[i].waveband in bands:
                if images[i].waveband in cbands:
                    pass
                else:
                    cbands.append(images[i].waveband)
        if len(cbands)==3: break

    if len(cbands) == 3:
        context['iracRGB'] = 'rgbirac%s' % md5unique
        context['iracBands'] = ' '.join(cbands)
    # -------------------------------------------------------------------------

    # Check if celery is accepting connections and submit job -----------------
    result = app.send_task('imagedb.tasks.status')
    time.sleep(0.1)
    status = result.ready()
    context['celeryStatus'] = status

    outCache = CACHE + '/' + request.session['md5unique'] + '/.complete'
    if os.access(outCache, os.R_OK):
        flag=False
        context['celeryStatus'] = True
        context['celeryID'] = result.task_id

    if flag:
        if status:
            result = app.send_task('imagedb.tasks.getImage', args=(req.id,))
            context["celeryID"] = result.task_id
            #print '****', result.task_id
            #res = AsyncResult(result.task_id)
            #print '****', res.ready()
    # -------------------------------------------------------------------------

    context['images'] = images

    if len(images) == 0:
        context['error_message'] = 'No images found.'

    req.success = True
    req.save()

    return render(request, 'imagedb/getimage.html', context)

casu/imagedb/templates/imagedb/collection.html
{% extends "base.html" %}



{% load staticfiles %}

{% block css.extra %}
<link rel="stylesheet" type="text/css" href="{% static 'imagedb/style.css' %}"/>
{% endblock css.extra %}

{% block js.extra %}
<script type="text/javascript" src="{% static 'casu/js/jquery.lazyload.js' %}"></script>

<script type="text/javascript">
	$(document).ready(function() {
		$('#search').keyup(function() {
			searchTable($(this).val());
		});
	});

    function searchTable(inputVal) {
	    var table = $('#tblData');
	    table.find('tr.data').each(function(index, row) {
			var allCells = $(row).find('td');
			var found = false;
			allCells.each(function(index, td) {
				var regExp = new RegExp(inputVal, 'i');
				if(regExp.test($(td).text())) {
					found = true;
					return false;
				}
			});
			if(found == true)$(row).show();else $(row).hide();
		});
    };
</script>

{% endblock js.extra %}

{% block sitetitle %}ImageDB{% endblock sitetitle %}

{% block cssmenu %}{% include "imagedb/cssmenu.html" %}{% endblock cssmenu %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% block pagename %}
Image Collections
{% endblock pagename %}


{% block content %}


<div class="bbox">

    <strong>Total number of images:</strong> {{ totalimages }}

    <div id="searchBox" style="float: right">
    <label for="search"><strong>Search </strong>     </label>
    <input type="text" id="search" style="width: 200px; border: 1px solid black;" />
    </div>
</div>

<div class="collection">




<table id="tblData" style="width: 100%">
    <tr>
        <th>Survey</th>
        <th>Field</th>
        <th>Telescope</th>
        <th>Instrument</th>
        <th>Waveband</th>
        <th>Number of images</th>
        <th>R.A. range</th>
        <th>Dec range</th>
        <th>PI</th>
        <th>Status</th>
    </tr>
    <tr></tr>
{% for item in collection %}
    {% if item.number %}
    <tr class="data">
        <td>{{ item.survey }}</td>
        <td>{{ item.field }}</td>
        <td>{{ item.telescope }}</td>
        <td>{{ item.instrument }}</td>
        <td>{{ item.filter }}</td>
        <td>{{ item.number }}</td>
        <td>[ {{ item.cenra__min|floatformat:2 }}, {{ item.cenra__max|floatformat:2 }} ]</td>
        <td>[ {{ item.cendec__min|floatformat:2 }}, {{ item.cendec__max|floatformat:2 }} ]</td>
        <td>{{ item.pi }}</td>
        <td>{{ item.status|capfirst }}</td>
    </tr>
    {% endif %}
{% endfor %}
</table>
</div>

{% endblock content%}

casu/imagedb/templates/imagedb/cssmenu.html
        <ul>
           <li class='active'><a href='index.html'><span>Home</span></a></li>
           <li><a href='#'><span>Products</span></a></li>
           <li><a href='#'><span>About</span></a></li>
           <li class='last'><a href='#'><span>Contact</span></a></li>
        </ul>

casu/imagedb/templates/imagedb/getimage.html
{% extends "base.html" %}



{% load staticfiles %}

{% block css.extra %}
<link rel="stylesheet" type="text/css" href="{% static 'imagedb/style.css' %}"/>
{% endblock css.extra %}

{% block js.extra %}
<script type="text/javascript" src="{% static 'casu/js/jquery.lazyload.js' %}"></script>
{% endblock js.extra %}

{% block head.extra %}
<script type="text/javascript" charset="utf-8">
$(document).ready(function(){

    $( "#toggleResults" ).click(function() {
        $( "#queryResults" ).toggle( "slow", function() {
            // Animation complete.
        });
    });

    $('#getimage').submit(function(){
        $('input[type=submit]', this).attr('disabled', 'disabled');
    });

    $(function() {
        $("img.lazy").lazyload({
            effect : "fadeIn"
        });
    });

    var i = setInterval( function() {
        $.ajax({
            url: $("#checkStatus").html(),
            dataType: 'json',
            success: function(json) {

                if (json.status == true) {
                    clearInterval(i);
                    $("#imageWait").hide();
                    $("#imageDownload").show();
                    $("#imageList").show();

                   }
            },
            error: function() {
                clearInterval(i);
            }
        });
        }, 1000);

	// hide #back-top first
	$("#back-top").hide();

	// fade in #back-top
	$(function () {
		$(window).scroll(function () {
			if ($(this).scrollTop() > 100) {
				$('#back-top').fadeIn();
			} else {
				$('#back-top').fadeOut();
			}
		});

		// scroll body to 0px on click
		$('#back-top a').click(function () {
			$('body,html').animate({
				scrollTop: 0
			}, 800);
			return false;
		});
	});

});


</script>
{% endblock head.extra %}

{% block sitetitle %}ImageDB{% endblock sitetitle %}




{% block pagename %}
Postage Stamp
{% endblock pagename %}


{% block content %}
<span id="checkStatus" style="display: none"> {% url 'imagedb:getStatus' celeryID %} </span>


<div class="getImage-form">
    <h1>Query Form</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form id="getimage" action="{% url 'imagedb:getImage' %}" method="post">
    {% csrf_token %}

    {% csrf_token %}
    <table>
        <tr>
            <td valign="top" style="padding: 1em">
                <label>R.A. (degrees)</label>
                <input type="text" name="ra" value="{{ ra }}"><br clear="left"/>

                <label>Dec (degrees)</label>
                <input type="text" name="dec" value="{{ dec }}"><br clear="left"/>

                <label>Size (arcsec)</label>
                <input type="text" name="size" value="{{ size }}"><br clear="left"/>

                <label>Options</label>
                <input type="text" name="options" value="{{ options }}"><br clear="left"/>
            </td>
            <!--
            <td valign="top"  style="padding: 1em; border-left: 1px solid silver">
                <input type="checkbox" name="download" value="download" > Stage results for download
            </td>
            -->
        </tr>
    </table>

    <input type="submit" class="getImage-submit" value="Submit"/>
</form>
</div>

{% if images %}

<div style="padding: 0 1em; background-color: #F7F7F7; box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3); border-radius: 2px;">
    <h3 style="display: block; border-bottom: 1px solid #ccc; padding: 1em">Query Results &nbsp; [ <span id="toggleResults" style="font-size: small">toggle</span> ]</h3>
    <table id='queryResults' style="width: 100%;">
        <tr style="background-color: #ccc">
            <th></th>
            <th>Image Name</th>
            <th>Object</th>
            <th>Coordintes</th>
            <th>Waveband</th>
            <th>Instrument</th>
            <th>Additional Information</th>
        </tr>
        {% for img in images %}
        <tr>
            <td>
                {% if img.avail %}
                <span style="background-color: green; padding: 0 0.25em">&nbsp;</span>
                {% else %}
                <span style="background-color: red; padding: 0 0.25em">&nbsp;</span>
                {% endif %}

            </td>
            <td>{{img.filename}}[{{img.extno}}]</td>
            <td>{{img.objname}}</td>
            <td>{{img.cencoords}}</td>
            <td>{{img.waveband}}</td>
            <td>{{img.instrument}}</td>
            <td>{{img.addinfo}}</td>
        </tr>
        {% endfor %}
    </table>
    <br/>
</div>

<!--p>Download all stamps: [ <a href="#">PNG</a> ] &nbsp; [ <a href="#">FITS</a> ] </p-->

{% if celeryStatus %}
<div style="padding: 0 1em; background-color: #F7F7F7; box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3); border-radius: 2px;">
<h3 style="display: block; border-bottom: 1px solid #ccc; padding: 1em">Postage Stamps
    <a id="imageDownload" href="{% url 'imagedb:getTar' md5unique %}" style="display: none; margin-left: 6em; border: 1px solid silver; font-size: small; background-color: #ccffff; padding: 4px; text-decoration: none">Download tar file</a>
</h3>
<div id="imageWait" style="height: 300px; width: 100%; text-align: center">

    <p>Creating stamps.... please wait</p>

</div>
<ul id="imageList" style="list-style-type: none;  display: none">
    {% if vistaRGB %}
    <li style="display: inline; float: left; border: 0px solid silver; padding: 0.0em">
        <table>
            <tr>
                <td style="text-align: center"> VIRCAM Colour Image <br/> &nbsp; {{vistaBands0}} &nbsp; </td>
            </tr>
            <tr>
                <td width="440px" height="410px" style="text-align: center">
                    <img class="lazy" src="{% static 'casu/ajax-loader.png' %}"
                         data-original="{% url 'imagedb:getImageCache' vistaRGB %}"></img>
                </td>
            </tr>
        </table>
    </li>
    {% endif %}
    {% if vstRGB %}
    <li style="display: inline; float: left; border: 0px solid silver; padding: 0.0em">
        <table>
            <tr>
                <td style="text-align: center"> OMEGACAM Colour Image <br/> &nbsp; {{vstBands0}} &nbsp;</td>
            </tr>
            <tr>
                <td width="440px" height="410px" style="text-align: center">
                    <img class="lazy" src="{% static 'casu/ajax-loader.png' %}"
                         data-original="{% url 'imagedb:getImageCache' vstRGB %}"></img>
                </td>
            </tr>
        </table>
    </li>
    {% endif %}
    {% if wfcRGB %}
    <li style="display: inline; float: left; border: 0px solid silver; padding: 0.0em">
        <table>
            <tr>
                <td style="text-align: center"> WFC Colour Image <br/> &nbsp; {{wfcBands0}} &nbsp;</td>
            </tr>
            <tr>
                <td width="440px" height="410px" style="text-align: center">
                    <img class="lazy" src="{% static 'casu/ajax-loader.png' %}"
                         data-original="{% url 'imagedb:getImageCache' wfcRGB %}"></img>
                </td>
            </tr>
        </table>
    </li>
    {% endif %}
    {% if iracRGB %}
    <li style="display: inline; float: left; border: 0px solid silver; padding: 0.0em">
        <table>
            <tr>
                <td style="text-align: center"> IRAC Colour Image <br/> &nbsp; {{iracBands0}} &nbsp;</td>
            </tr>
            <tr>
                <td width="440px" height="410px" style="text-align: center">
                    <img class="lazy" src="{% static 'casu/ajax-loader.png' %}"
                         data-original="{% url 'imagedb:getImageCache' iracRGB %}"></img>
                </td>
            </tr>
        </table>
    </li>
    {% endif %}
    {% for img in images %}
    {% if img.avail %}
    <li style="display: inline; float: left; border: 0px solid silver; padding: 0.0em">
        <table>
            <tr>
                <td style="text-align: center">{{img.instrument}} - {{img.waveband}}<br/>{{img.filename}}</td>
            </tr>
            <tr>
                <td width="440px" height="440px" style="text-align: center">
                    <img class="lazy" src="{% static 'casu/ajax-loader.png' %}"
                         data-original="{% url 'imagedb:getImageCache' img.md5hash %}"></img>
                </td>
            </tr>
        </table>
    </li>
    {% endif %}
    {% endfor %}
</ul>

<br clear="left"/>
</div>
{% endif %}

{% endif %}

    <p id="back-top">
		<a href="#top"><span></span>Back to Top</a>
	</p>

{% endblock content%}

casu/imagedb/templates/imagedb/getimagelocal.html
{% extends "base.html" %}

{% load staticfiles %}

{% block css.extra %}
<link rel="stylesheet" type="text/css" href="{% static 'imagedb/style.css' %}" />
{% endblock css.extra%}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% block pagename %}
Local Postage Stamp
{% endblock pagename %}


{% block content %}

{% if imagedata %}
<div id="imagedata">
<img alt="Embedded Image" src="{{ imagedata }}"/>
</div>
{% endif %}

<form id="getimagelocal" action="{% url 'imagedb:getImageLocal' %}" method="post">
{% csrf_token %}
<label>R.A. (degrees)</label>
<input type="text" name="ra" value="{{ ra }}"><br/>

<label>Dec (degrees)</label>
<input type="text" name="dec" value="{{ dec }}"><br/>

<label>Size (arcsec)</label>
<input type="text" name="size" value="{{ size }}"><br/>

<label>Image [Hdu]</label>
<input class="image" type="text" name="image" value="{{ image }}">
<input class="hdu" type="text" name="hdu" value="{{ hdu }}"><br/>

<label>Options</label>
<input type="text" name="options" value="{{ options }}"><br/>


<input type="submit" value="Submit" />
</form>

{% endblock content%}

casu/imagedb/templates/imagedb/index.html
{% extends "base.html" %}



{% load staticfiles %}

{% block css.extra %}
<link rel="stylesheet" type="text/css" href="{% static 'imagedb/style.css' %}"/>
{% endblock css.extra %}

{% block js.extra %}
{% endblock js.extra %}

{% block head.extra %}

{% endblock head.extra %}

{% block sitetitle %}ImageDB{% endblock sitetitle %}




{% block pagename %}
Index
{% endblock pagename %}


{% block content %}

{% endblock content%}